name: Publish Java-SDK

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "8"
          cache: "gradle"

      - name: Publish JavaSDK
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.inputs.versionName }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
          SECRET_FILE_DATA: ${{ secrets.SECRET_FILE_DATA }}
        run: |
          export GPG_TTY=$(tty)
          mkdir -p ~/.gradle/
          ln -s /usr/local/bin/gpg /usr/local/bin/gpg2
          echo -n "$SECRET_FILE_DATA" | base64 --decode | gpg --import --passphrase "$ORG_GRADLE_PROJECT_signingInMemoryKeyPassword" --batch
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
          ./gradlew clean build publish closeAndReleaseSonatypeStagingRepository -x test